language: objective-c
install:
- brew install cmake
script: script/cibuild
notifications:
  email: false
  campfire:
    on_success: always
    on_failure: always
    template:
      - "Build %{build_url} of %{repository}: %{message}"